// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpdzrrbxcgupnldjmqsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZHpycmJ4Y2d1cG5sZGptcXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTc3MzYsImV4cCI6MjA1ODEzMzczNn0.m-8TKNWfT4e2Qs_DxD0tlsaxAexh3fxTXF6V8iOKkno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);